### ISSUE TITLE
Dead link in the Large Data section

### ISSUE THREAD

**Issue by pletzer** [carpentries-lab/python-aos-lesson#47]
The link to the instructor notes (https://carpentrieslab.github.io/python-aos-lesson/guide/index.html) is dead. Thanks for fixing.

**Comment by DamienIrving** [comment]
Thanks for spotting this, @pletzer! They put a hyphen in the carpentries-lab GitHub organisation name (i.e. https://github.com/carpentries-lab) a few months ago and clearly I didn't catch all the old links. I've updated everything in https://github.com/carpentries-lab/python-aos-lesson/commit/89cedb00b6f73aa86c19695dd2799ad949b0f60a.
