### ISSUE TITLE
conda-forge channel needs full path or can't be added

### ISSUE THREAD

**Issue by jonnyhtw** [carpentries-lab/python-aos-lesson#50]
Hi there, 

This page needs to be edited to include the full URL of the `conda-forge` channel. Otherwise it fails.

This is the image...

![image](https://user-images.githubusercontent.com/12940715/151476202-7a3b9252-a0c3-4312-bf92-846bfe4465ad.png)

This is the edit that I needed to make...

![image](https://user-images.githubusercontent.com/12940715/151476305-c05a08f2-4d8c-4af9-b6fe-6f1da5f1b47a.png)

Happy to work on this myself with a bit of guidance since I haven't used GitHub pages before.

Thanks!

**Comment by jonnyhtw** [comment]
FYI guidance on this is on the conda-forge website [here](https://conda-forge.org/docs/user/introduction.html). 😄

**Comment by DamienIrving** [comment]
Thanks for spotting this, @jonnyhtw!

If you fork this repository, replace `fig/01-navigator-conda-forge.png` with your image (keep the file name exactly the same) and then submit a pull request, that will do the trick :smile:

**Comment by jonnyhtw** [comment]
> Thanks for spotting this, @jonnyhtw!
> 
> If you fork this repository, replace `fig/01-navigator-conda-forge.png` with your image (keep the file name exactly the same) and then submit a pull request, that will do the trick 😄

Thanks! I *think* I've done that now... 😆 

This is the issue number, #51.
