### ISSUE TITLE
Transition to new lesson infrastructure?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-lab/python-aos-lesson#61]
Would you be interested in help migrating this lesson to the new lesson infrastructure, The Carpentries Workbench? We recently published documentation for a semi-automated transition workflow, and I am also happy to work on this if you would like help?

**Comment by DamienIrving** [comment]
Hi, @tobyhodges. Apologies for the delay in responding - I'd love some help transitioning to the new lesson infrastructure. Is [this](https://carpentries.github.io/sandpaper-docs/migrating-from-styles.html) the documentation you're referring to?

**Comment by tobyhodges** [comment]
Hey @DamienIrving yes that's the correct page. The setup is a bit fiddly, unfortunately, but quite a few community members have been able to transition their own lessons by following it. I have limited capacity to support migration of community-owned lessons, but I am keen to see all lessons in The Carpentries Lab adopting the Workbench. So if you find that the process is too difficult to follow yourself, please let me know here and I will set aside some time to work through it for you.

**Comment by DamienIrving** [comment]
Thanks, @tobyhodges. I was able to successfully transition to the Workbench. I had one minor hiccup along the way relating pandoc versions, so I've posted an issue with the fix I found: https://github.com/carpentries/lesson-transition/issues/102
